---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ttx-api
  namespace: ttx
spec:
  selector:
    matchLabels:
      app: ttx-api
  template:
    metadata:
      labels:
        app: ttx-api
    spec:
      volumes:
        - name: ttx-dataprotection
          persistentVolumeClaim:
            claimName: ttx-dataprotection
      imagePullSecrets:
        - name: ttx-regcreds
      containers:
        - name: api
          image: ghcr.io/ttxdev/ttx.api:main
          imagePullPolicy: Always
          resources:
            limits:
              memory: "250Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: ttx-config
          volumeMounts:
            - name: ttx-dataprotection
              mountPath: /var/ttx/keys

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ttx-jobs
  namespace: ttx
spec:
  selector:
    matchLabels:
      app: ttx-jobs
  replicas: 1 # jobs is not scalable :(
  template:
    metadata:
      labels:
        app: ttx-jobs
    spec:
      imagePullSecrets:
        - name: ttx-regcreds
      containers:
        - name: jobs
          image: ghcr.io/ttxdev/ttx.private:main
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: ttx-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ttx-web
  namespace: ttx
spec:
  selector:
    matchLabels:
      app: ttx-web
  template:
    metadata:
      labels:
        app: ttx-web
    spec:
      imagePullSecrets:
        - name: ttx-regcreds
      containers:
        - name: web
          image: ghcr.io/ttxdev/ttx.web:main
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: ttx
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 6379
