---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ttx-api
  namespace: ttx
spec:
  selector:
    matchLabels:
      app: ttx-api
  replicas: 4
  template:
    metadata:
      labels:
        app: ttx-api
    spec:
      volumes:
        - name: dataprotection
          persistentVolumeClaim:
            claimName: ttx-dataprotection
      imagePullSecrets:
        - name: ttx-regcreds
      containers:
      - name: api
        image: ghcr.io/ttxdev/ttx.api:main
        imagePullPolicy: Always
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        envFrom:
          - secretRef:
              name: ttx-config
        volumeMounts:
          - name: dataprotection
            mountPath: /var/ttx/keys

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ttx-web
  namespace: ttx
spec:
  selector:
    matchLabels:
      app: ttx-web
  replicas: 6
  template:
    metadata:
      labels:
        app: ttx-web
    spec:
      imagePullSecrets:
        - name: ttx-regcreds
      containers:
      - name: web
        image: ghcr.io/ttxdev/ttx.web:main
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ttx-bot
  namespace: ttx
spec:
  selector:
    matchLabels:
      app: ttx-bot
  template:
    metadata:
      labels:
        app: ttx-bot
    spec:
      imagePullSecrets:
        - name: ttx-regcreds
      containers:
      - name: bot
        image: ghcr.io/ttxdev/ttx.bot:main
        imagePullPolicy: Always
        resources:
        envFrom:
          - secretRef:
              name: ttx-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ttx-streammonitor
  namespace: ttx
spec:
  selector:
    matchLabels:
      app: ttx-streammonitor
  template:
    metadata:
      labels:
        app: ttx-streammonitor
    spec:
      imagePullSecrets:
        - name: ttx-regcreds
      containers:
      - name: streammonitor
        image: ghcr.io/ttxdev/ttx.streammonitor:main
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: ttx-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ttx-portfoliomonitor
  namespace: ttx
spec:
  selector:
    matchLabels:
      app: ttx-portfoliomonitor
  template:
    metadata:
      labels:
        app: ttx-portfoliomonitor
    spec:
      imagePullSecrets:
        - name: ttx-regcreds
      containers:
      - name: portfoliomonitor
        image: ghcr.io/ttxdev/ttx.portfoliomonitor:main
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: ttx-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: ttx
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 6379
