apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ttx
  namespace: ttx
  labels:
    name: ttx
spec:
  rules:
    - host: api.ttx.gg
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: ttx-api
                port:
                  number: 3030
    - host: ttx.gg
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: ttx-web
                port:
                  number: 3031
