---
apiVersion: v1
kind: Service
metadata:
  name: ttx-api
  namespace: ttx
spec:
  type: ClusterIP
  selector:
    app: ttx-api
  ports:
    - port: 3000
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: ttx-web
  namespace: ttx
spec:
  type: ClusterIP
  selector:
    app: ttx-web
  ports:
    - port: 3001
      targetPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  namespace: ttx
  name: redis
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
