---
apiVersion: v1
kind: Service
metadata:
  name: ttx-api
  namespace: ttx
spec:
  type: ClusterIP
  selector:
    app: ttx-api
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.name: TTX.Session.Sticky
    traefik.ingress.kubernetes.io/service.sticky.cookie.sameSite: lax
    traefik.ingress.kubernetes.io/service.sticky.cookie.secure: "true"
  ports:
    - port: 3030
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: ttx-web
  namespace: ttx
spec:
  type: ClusterIP
  selector:
    app: ttx-web
  ports:
    - port: 3031
      targetPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  namespace: ttx
  name: redis
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
